import "./globals.css";
import type { Metadata } from "next";
import { NextAuthProvider } from "./Provider";
import Header from "./components/Header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Next-auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Header />
          <Toaster position="top-right" expand={true} closeButton richColors />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}